# Generated by Django 5.2.7 on 2025-11-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile_avatar_profile_nick_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='./app/static/main/default.jpg', upload_to='profile_pics'),
        ),
    ]
